<?php
declare(strict_types=1);

if (parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) === '/healthz') {
    header('Content-Type: text/plain; charset=utf-8');
    echo 'ok';
    exit;
}

header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');
header('Referrer-Policy: strict-origin-when-cross-origin');
header('Permissions-Policy: camera=(), microphone=(), geolocation=()');
header("Content-Security-Policy: default-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; img-src 'self' data:; form-action 'self'; base-uri 'self'; frame-ancestors 'none'");
$secureCookieSetting = getenv('SESSION_COOKIE_SECURE');
$secureCookie = $secureCookieSetting === false
    ? getenv('APP_ENV') === 'production'
    : filter_var($secureCookieSetting, FILTER_VALIDATE_BOOLEAN);
session_set_cookie_params(['httponly'=>true,'secure'=>$secureCookie,'samesite'=>'Lax']);
session_start();

$pages = [
    'home' => ['title' => 'Integrated security. Built on intelligence.', 'eyebrow' => 'X-SECURITY · INTEGRATED CAPABILITY', 'intro' => 'We bring trained people, protective intelligence, investigations and cybersecurity together to help organizations and individuals operate with greater confidence.', 'type' => 'home'],
    'about' => ['title' => 'Capability built around people, preparation and trust.', 'eyebrow' => 'ABOUT X-SECURITY', 'intro' => 'Our mission is to develop disciplined security professionals and deliver integrated protection, investigation, technology and risk-management services.', 'type' => 'about'],
    'services' => ['title' => 'One security partner. The right capability for the problem.', 'eyebrow' => 'OUR SERVICES', 'intro' => 'Start with the risk you need to address. We shape a proportionate response from specialist teams across four connected divisions.', 'type' => 'services'],
    'investigations' => ['title' => 'When the facts matter, investigate properly.', 'eyebrow' => 'PRIVATE INVESTIGATION', 'intro' => 'Structured, confidential investigations supported by research, technology and experienced specialists.', 'type' => 'division', 'problem' => 'Important decisions are difficult when information is incomplete, inconsistent or unverified.', 'solution' => 'We scope each matter carefully, use lawful and proportionate methods, and deliver clear findings that support the next decision.', 'items' => ['Corporate and workplace investigations', 'Due diligence and background screening', 'Fraud and misconduct inquiries', 'Investigative research and litigation support', 'Missing-person inquiries and evidence coordination']],
    'cybersecurity' => ['title' => 'Understand your exposure. Strengthen your defenses.', 'eyebrow' => 'CYBERSECURITY & TECHNOLOGY', 'intro' => 'Practical defensive security that helps you identify weaknesses, respond to incidents and protect critical information.', 'type' => 'division', 'problem' => 'Digital exposure can affect operations, reputation and personal safety, often alongside physical risks.', 'solution' => 'Our authorized, defensive services help you understand risk and improve resilience without unnecessary complexity.', 'items' => ['Cybersecurity and vulnerability assessments', 'Authorized penetration testing', 'Incident response and digital forensics', 'Security architecture and audit', 'Threat intelligence and awareness training']],
    'protection' => ['title' => 'Protection delivered with discretion and professionalism.', 'eyebrow' => 'EXECUTIVE & VENUE PROTECTION', 'intro' => 'Trained, supervised and professional personnel for people, events and venues.', 'type' => 'division', 'problem' => 'People and venues need security that supports a confident experience while managing risk calmly.', 'solution' => 'We plan around the assignment, coordinate with your team and deliver a proportionate, well-briefed deployment.', 'items' => ['Executive and personal protection', 'Event and venue security', 'Access control and security planning', 'Travel protection and security escorts', 'VIP movement coordination']],
    'risk' => ['title' => 'Understand the risk before responding to it.', 'eyebrow' => 'PROTECTIVE INTELLIGENCE & RISK', 'intro' => 'Clear assessments and practical security plans that help you make informed decisions before incidents occur.', 'type' => 'division', 'problem' => 'Without a clear view of threats and vulnerabilities, security investments can be poorly targeted.', 'solution' => 'We assess context, identify priorities and shape a practical plan, drawing on specialist capabilities when needed.', 'items' => ['Executive and travel risk assessments', 'Site and event security assessments', 'Threat assessment and monitoring', 'Crisis preparedness and security planning', 'Corporate security audits and advisory']],
    'training' => ['title' => 'Operational capability begins with training.', 'eyebrow' => 'TRAINING PROGRAMS', 'intro' => 'A role-based development pathway that builds professional judgment, practical skill and continuous improvement.', 'type' => 'training'],
    'careers' => ['title' => 'Build a career in professional security.', 'eyebrow' => 'CAREERS', 'intro' => 'Join a learning culture where integrity, self-control and professional standards matter as much as specialist skill.', 'type' => 'careers'],
    'contact' => ['title' => 'Start with a confidential conversation.', 'eyebrow' => 'CONTACT & INQUIRY', 'intro' => 'Tell us what you need at a high level. A specialist will help define an appropriate next step.', 'type' => 'contact'],
    'compliance' => ['title' => 'Trust is earned through accountable practice.', 'eyebrow' => 'CERTIFICATIONS & COMPLIANCE', 'intro' => 'Our operating principles put lawful practice, confidentiality, safety and verifiable credentials first.', 'type' => 'compliance'],
    'cases' => ['title' => 'A considered response. A clearer outcome.', 'eyebrow' => 'CLIENT SUCCESS', 'intro' => 'Illustrative engagement patterns show how connected capabilities can support better decisions. Client details are withheld to protect confidentiality.', 'type' => 'cases'],
    'resources' => ['title' => 'Practical thinking for a changing risk landscape.', 'eyebrow' => 'INSIGHTS & RESOURCES', 'intro' => 'Guidance on protective security, cyber resilience, investigations and organizational preparedness.', 'type' => 'resources'],
    'faq' => ['title' => 'Answers to common questions.', 'eyebrow' => 'FREQUENTLY ASKED QUESTIONS', 'intro' => 'A useful starting point for understanding how we work and how to begin an engagement.', 'type' => 'faq'],
];

$services = [
    ['id'=>'investigations','num'=>'01','title'=>'Private Investigation','desc'=>'Find facts, assess evidence and support informed action.','tag'=>'INVESTIGATE'],
    ['id'=>'cybersecurity','num'=>'02','title'=>'Cybersecurity & Technology','desc'=>'Identify digital exposure and build stronger defenses.','tag'=>'SECURE'],
    ['id'=>'protection','num'=>'03','title'=>'Executive & Venue Protection','desc'=>'Professional protection for people, events and places.','tag'=>'PROTECT'],
    ['id'=>'risk','num'=>'04','title'=>'Protective Intelligence & Risk','desc'=>'Understand threats and prioritize practical safeguards.','tag'=>'ASSESS'],
];
$nav = ['Services'=>['services','investigations','cybersecurity','protection','risk'],'About'=>['about','compliance','cases'],'Training'=>['training'],'Careers'=>['careers'],'Resources'=>['resources','faq']];
$slug = (string)($_GET['page'] ?? 'home');
if (!isset($pages[$slug])) { http_response_code(404); $slug='home'; }
$page = $pages[$slug];
$escape = static fn(string $v): string => htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
$sent = false; $error = '';
if ($slug === 'contact' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $token = (string)($_POST['csrf'] ?? '');
    if (!hash_equals((string)($_SESSION['csrf'] ?? ''), $token)) { http_response_code(403); $error='Your session expired. Please refresh and try again.'; }
    elseif (getenv('APP_ENV') === 'production') { http_response_code(503); $error='The inquiry form is not configured yet. Please contact X-Security directly.'; }
    elseif (trim((string)($_POST['website'] ?? '')) !== '') { $sent=true; }
    else {
        $name=trim((string)($_POST['name']??'')); $email=trim((string)($_POST['email']??'')); $need=trim((string)($_POST['need']??''));
        if ($name==='' || !filter_var($email,FILTER_VALIDATE_EMAIL) || $need==='') $error='Please provide your name, a valid email and the type of support you need.';
        else { $sent=true; }
    }
}
if (empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(32));
function linkTo(string $id): string { return '?page='.rawurlencode($id); }
function serviceCards(array $services, callable $escape): void { foreach($services as $s): ?>
    <a class="service-card" href="<?= linkTo($s['id']) ?>"><span class="card-top"><span><?= $escape($s['num']) ?></span><span class="arrow">↗</span></span><span class="eyebrow"><?= $escape($s['tag']) ?></span><h3><?= $escape($s['title']) ?></h3><p><?= $escape($s['desc']) ?></p><span class="text-link">Explore capability <span>→</span></span></a>
<?php endforeach; }
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="X-Security integrates protective intelligence, investigations, cybersecurity, protection and professional training.">
  <meta name="theme-color" content="#101b22"><title><?= $escape($page['title']) ?> | X-Security</title>
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/site.css"><script defer src="assets/js/site.js"></script>
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="header-inner">
  <a class="brand" href="<?= linkTo('home') ?>" aria-label="X-Security home"><span class="brand-mark">X</span><span class="brand-name">X-SECURITY<small>INTELLIGENCE · PROTECTION · TRAINING</small></span></a>
  <button class="menu-toggle" aria-expanded="false" aria-controls="main-nav"><span></span><span></span><span class="sr-only">Menu</span></button>
  <nav id="main-nav" class="main-nav" aria-label="Main navigation">
    <?php foreach($nav as $label=>$items): $active=in_array($slug,$items,true); ?><div class="nav-group"><a class="nav-link <?= $active?'active':'' ?>" href="<?= linkTo($items[0]) ?>"><?= $escape($label) ?></a><div class="nav-menu"><?php foreach($items as $item): ?><a href="<?= linkTo($item) ?>" <?= $slug===$item?'aria-current="page"':'' ?>><?= $escape($pages[$item]['eyebrow']) ?></a><?php endforeach; ?></div></div><?php endforeach; ?>
    <a class="button button-small" href="<?= linkTo('contact') ?>">Request consultation <span>↗</span></a>
  </nav>
</div></header>
<main id="main">
<?php if($page['type']==='home'): ?>
  <section class="hero hero-home"><div class="hero-grid"><div class="hero-copy"><p class="eyebrow light"><span class="live-dot"></span> INTEGRATED SECURITY CAPABILITY</p><h1>Integrated security.<br><em>Built on intelligence.</em></h1><p class="hero-lead">We bring trained people, protective intelligence, investigations and cybersecurity together to help you move forward with confidence.</p><div class="hero-actions"><a class="button button-accent" href="<?= linkTo('contact') ?>">Discuss your requirements <span>↗</span></a><a class="button button-ghost" href="<?= linkTo('services') ?>">Explore our services <span>→</span></a></div><div class="hero-note"><span class="note-line"></span><span>ASSESS <b>→</b> DESIGN <b>→</b> PROTECT</span></div></div>
  <div class="hero-visual" aria-label="Abstract layered security network illustration" role="img"><div class="orb orb-one"></div><div class="orb orb-two"></div><div class="visual-grid"></div><div class="radar-ring ring-a"></div><div class="radar-ring ring-b"></div><div class="radar-ring ring-c"></div><div class="crosshair">X</div><div class="visual-label label-top"><span class="live-dot"></span> OPERATING PICTURE <b>LIVE</b></div><div class="visual-label label-bottom"><span>01 / 04</span><b>CONNECTED CAPABILITIES</b></div><div class="visual-point point-one"></div><div class="visual-point point-two"></div><div class="visual-point point-three"></div></div></div><div class="hero-footer"><span>INTEGRITY IN EVERY ENGAGEMENT</span><span>CONFIDENTIAL · PROFESSIONAL · PROPORTIONATE</span></div></section>
  <section class="trust-strip"><span class="eyebrow">OUR OPERATING PRINCIPLES</span><div><span>Intelligence-led</span><span>Training-first</span><span>Integrated response</span><span>Professional standards</span></div></section>
  <section class="section section-services"><div class="section-head"><div><p class="eyebrow">CONNECTED BY DESIGN</p><h2>Four disciplines.<br><em>One considered response.</em></h2></div><p class="section-intro">A client challenge rarely fits neatly into one category. Our connected teams make it easier to bring together the right expertise, at the right time.</p></div><div class="service-grid"><?php serviceCards($services,$escape); ?></div><div class="section-bottom"><a class="text-link" href="<?= linkTo('services') ?>">See how our capabilities connect <span>→</span></a></div></section>
  <section class="method-section"><div class="method-visual"><div class="method-mark">X<span></span></div><div class="method-caption">A CLEARER VIEW.<br>A MORE CONSIDERED RESPONSE.</div></div><div class="method-copy"><p class="eyebrow light">HOW WE WORK</p><h2>Start with the risk.<br><em>Shape the response.</em></h2><p>We begin by understanding the context, then build a practical plan around your people, operations and priorities. Specialist services are coordinated where the challenge calls for them.</p><div class="method-steps"><div><b>01</b><span><strong>Assess</strong><small>Understand the context and exposure.</small></span></div><div><b>02</b><span><strong>Design</strong><small>Set priorities and shape a proportionate plan.</small></span></div><div><b>03</b><span><strong>Protect</strong><small>Coordinate the expertise to put it into action.</small></span></div></div><a class="text-link link-light" href="<?= linkTo('about') ?>">Meet X-Security <span>→</span></a></div></section>
  <section class="section training-band"><div><p class="eyebrow">PEOPLE ARE THE FOUNDATION</p><h2>Capability is developed.<br><em>Not assumed.</em></h2><p>Our training-first culture gives every specialist a common foundation in conduct, communication and sound judgment, followed by role-specific development.</p><a class="button button-dark" href="<?= linkTo('training') ?>">Explore training <span>↗</span></a></div><div class="pathway"><div class="path-line"></div><?php foreach(['Foundation','Assessment','Specialization','Deployment','Development'] as $i=>$step): ?><div class="path-step"><span>0<?= $i+1 ?></span><b><?= $escape($step) ?></b></div><?php endforeach; ?></div></section>
  <section class="proof-section"><div class="proof-number">X<span></span></div><div><p class="eyebrow light">CONFIDENCE THROUGH CLARITY</p><h2>Serious about security.<br><em>Measured in how we work.</em></h2><p>Professional conduct, careful scoping, clear reporting and confidentiality are part of the service—not extras.</p><a class="text-link link-light" href="<?= linkTo('compliance') ?>">Our standards and commitments <span>→</span></a></div><div class="proof-aside"><span class="proof-line"></span><p>VERIFIABLE CREDENTIALS<br>ONLY. NO UNSUPPORTED CLAIMS.</p></div></section>
  <section class="cta-section"><div><p class="eyebrow">THE FIRST STEP IS A CONVERSATION</p><h2>What does better<br><em>security look like for you?</em></h2></div><a class="button button-accent" href="<?= linkTo('contact') ?>">Tell us what you need <span>↗</span></a></section>
<?php else: ?>
  <section class="page-hero"><div class="page-hero-inner"><div><p class="eyebrow"><span class="live-dot"></span><?= $escape($page['eyebrow']) ?></p><h1><?= $escape($page['title']) ?></h1><p class="hero-lead"><?= $escape($page['intro']) ?></p><?php if($page['type']!=='contact'): ?><a class="button button-accent" href="<?= linkTo('contact') ?>">Request a consultation <span>↗</span></a><?php endif; ?></div><div class="page-hero-art" aria-hidden="true"><span class="art-x">X</span><span class="art-orbit"></span><span class="art-axis"></span><small>ASSESS · DESIGN · PROTECT</small></div></div></section>
  <div class="breadcrumb"><a href="<?= linkTo('home') ?>">Home</a><span>/</span><span><?= $escape($page['eyebrow']) ?></span></div>
  <section class="section page-content">
  <?php if($page['type']==='about'): ?>
    <div class="section-head"><div><p class="eyebrow">OUR PURPOSE</p><h2>Develop people.<br><em>Deliver confidence.</em></h2></div><div class="rich-copy"><p>Our mission is to develop highly disciplined security professionals and deliver integrated protection, investigation, technology and risk-management services.</p><p>We aim to become a trusted security organization recognized for bringing professional personnel, rigorous training, intelligence and technology together around complex security problems.</p></div></div>
    <div class="principle-grid"><?php foreach([['01','Training-first culture','We develop people against defined competencies.'],['02','Integrated security','Specialists collaborate across physical, digital and investigative needs.'],['03','Intelligence-led','Decisions start with context, assessment and evidence.'],['04','Professionalism','Conduct, communication, documentation and confidentiality are part of quality.']] as $x): ?><article><span><?= $x[0] ?></span><h3><?= $escape($x[1]) ?></h3><p><?= $escape($x[2]) ?></p></article><?php endforeach; ?></div>
    <div class="callout"><p class="eyebrow">A NOTE ON LEADERSHIP</p><h3>Accountable leadership is a core part of trust.</h3><p>Leadership biographies and photographs will be published after approval. We do not invent credentials or experience claims.</p></div>
  <?php elseif($page['type']==='services'): ?><div class="section-head"><div><p class="eyebrow">SPECIALIST DIVISIONS</p><h2>Find the capability<br><em>that fits your challenge.</em></h2></div><p class="section-intro">Every engagement begins with a clear brief and an appropriate scope. You can approach one division directly or discuss a connected requirement.</p></div><div class="service-grid"><?php serviceCards($services,$escape); ?></div>
  <?php elseif($page['type']==='division'): ?><div class="section-head division-intro"><div><p class="eyebrow">THE CHALLENGE</p><h2><?= $escape($page['problem']) ?></h2></div><div class="rich-copy"><p><?= $escape($page['solution']) ?></p><p>We agree the scope, responsibilities and appropriate safeguards before work begins. Services are delivered within applicable legal, privacy, safety and authorization requirements.</p></div></div><div class="capability-layout"><div><p class="eyebrow">SERVICE SCOPE</p><h2>Specialist support,<br><em>clearly defined.</em></h2><a class="button button-dark" href="<?= linkTo('contact') ?>">Discuss this service <span>↗</span></a></div><div class="capability-list"><?php foreach($page['items'] as $i=>$item): ?><div><span>0<?= $i+1 ?></span><b><?= $escape($item) ?></b><span class="plus">↗</span></div><?php endforeach; ?></div></div><div class="process-row"><p class="eyebrow">A CLEAR ENGAGEMENT PATH</p><?php foreach(['Brief','Scope','Deliver','Review'] as $i=>$x): ?><div><span>0<?= $i+1 ?></span><b><?= $escape($x) ?></b></div><?php endforeach; ?></div><div class="callout"><p class="eyebrow">INTEGRATED BY DESIGN</p><h3>Some challenges cross specialist boundaries.</h3><p>We can coordinate complementary capabilities in risk intelligence, investigations, cyber and protection where appropriate.</p><a class="text-link" href="<?= linkTo('services') ?>">Explore connected services <span>→</span></a></div>
  <?php elseif($page['type']==='training'): ?><div class="section-head"><div><p class="eyebrow">A CONTINUOUS DEVELOPMENT MODEL</p><h2>From foundation<br><em>to specialization.</em></h2></div><p class="section-intro">Core competencies are universal. Specialization and physical conditioning are matched to the role and assignment, with safety and legal requirements built in.</p></div><div class="training-steps"><?php foreach([['01','Foundation','Conduct, communication, awareness, first aid, reporting and professional security principles.'],['02','Assessment','Evaluate readiness against clear role-based competencies.'],['03','Specialization','Develop relevant skills across protection, investigations, cyber or risk intelligence.'],['04','Deployment','Apply capability with supervision, clear briefing and defined responsibilities.'],['05','Continuous development','Refresh skills, review performance and support career progression.']] as $x): ?><article><span><?= $x[0] ?></span><div><h3><?= $escape($x[1]) ?></h3><p><?= $escape($x[2]) ?></p></div></article><?php endforeach; ?></div><div class="capability-layout"><div><p class="eyebrow">LEARNING PATHWAYS</p><h2>Build a career<br><em>with direction.</em></h2></div><div class="capability-list"><?php foreach(['Protective operations','Investigative methods','Cybersecurity and technology','Protective intelligence','Team leadership and instruction'] as $i=>$x): ?><div><span>0<?= $i+1 ?></span><b><?= $escape($x) ?></b><span class="plus">↗</span></div><?php endforeach; ?></div></div><a class="button button-accent" href="<?= linkTo('contact') ?>">Enquire about training <span>↗</span></a>
  <?php elseif($page['type']==='careers'): ?><div class="section-head"><div><p class="eyebrow">WHO THRIVES HERE</p><h2>Character is a<br><em>professional skill.</em></h2></div><div class="rich-copy"><p>We value integrity, discipline, communication, emotional self-control and a commitment to learning. Fitness and technical expectations depend on the role.</p><p>We welcome capable candidates across operational, technical, analytical, instructional and business support pathways.</p></div></div><div class="principle-grid"><?php foreach([['01','Protection','Professional judgment and role-appropriate readiness.'],['02','Investigations','Curiosity, discretion and clear written communication.'],['03','Cybersecurity','Technical aptitude and a defensive mindset.'],['04','Risk intelligence','Structured analysis and practical advice.']] as $x): ?><article><span><?= $x[0] ?></span><h3><?= $escape($x[1]) ?></h3><p><?= $escape($x[2]) ?></p></article><?php endforeach; ?></div><div class="callout"><p class="eyebrow">APPLICATION PATHWAY</p><h3>Apply → Screening → Assessment → Interview → Training</h3><p>Current openings and the application email will be listed here when recruitment is active. Use the inquiry form to register interest; please do not send sensitive personal documents through an unverified channel.</p><a class="button button-dark" href="<?= linkTo('contact') ?>">Register your interest <span>↗</span></a></div>
  <?php elseif($page['type']==='compliance'): ?><div class="section-head"><div><p class="eyebrow">HOW WE EARN TRUST</p><h2>Responsible practice,<br><em>made visible.</em></h2></div><p class="section-intro">Credentials, licenses and insurance are shown only when verified, current and applicable to the service and jurisdiction.</p></div><div class="principle-grid"><?php foreach([['01','Lawful and authorized','Investigations and security testing are scoped and delivered within applicable legal authority.'],['02','Privacy and confidentiality','We limit information collection, manage it carefully and respect confidentiality obligations.'],['03','Safety and accountability','Operational responsibilities, supervision and escalation pathways are defined before deployment.'],['04','Verifiable credentials','Credential names, issuing bodies, validity and scope will be published after verification.']] as $x): ?><article><span><?= $x[0] ?></span><h3><?= $escape($x[1]) ?></h3><p><?= $escape($x[2]) ?></p></article><?php endforeach; ?></div><div class="callout"><p class="eyebrow">CREDENTIAL REGISTER</p><h3>Current licenses and certifications</h3><p>Verified company registrations, jurisdiction-specific licenses, professional credentials and insurance information can be added here as they are confirmed.</p></div>
  <?php elseif($page['type']==='cases'): ?><div class="case-grid"><?php foreach([['01','CORPORATE RISK','Bringing physical and digital exposure into one view','A multi-site organization needed a clearer picture of its security priorities. An assessment mapped key risks and produced a sequenced improvement plan.','Outcome: a prioritized, actionable security roadmap.'],['02','EXECUTIVE SUPPORT','Coordinating protective planning around a changing schedule','A client required discreet support across a time-sensitive program. Risk review and deployment planning helped align the team around changing requirements.','Outcome: a coordinated plan with clear roles and escalation.'],['03','INVESTIGATIVE SUPPORT','Turning fragmented information into decision-ready findings','A professional organization needed an independently scoped inquiry with careful documentation and privacy safeguards.','Outcome: structured findings to inform the client’s next steps.']] as $x): ?><article class="case-card"><span class="eyebrow"><?= $escape($x[1]) ?> · <?= $escape($x[0]) ?></span><h3><?= $escape($x[2]) ?></h3><p><?= $escape($x[3]) ?></p><b><?= $escape($x[4]) ?></b><small>Illustrative scenario. Not a claim of a completed client engagement.</small></article><?php endforeach; ?></div>
  <?php elseif($page['type']==='resources'): ?><div class="resource-grid"><?php foreach([['01','GUIDE','A practical starting point for a corporate security assessment','A structured way to identify priorities across people, sites, operations and technology.'],['02','BRIEFING','Reducing digital risk through better security habits','How clear policies and role-based awareness can strengthen everyday cyber resilience.'],['03','CHECKLIST','Planning security for an event or venue','Key considerations for access, responsibilities, communications and contingency planning.'],['04','INSIGHT','When an investigation needs specialist support','How careful scoping, lawful methods and clear reporting help decision-makers.']] as $x): ?><article><span><?= $x[0] ?> / <?= $escape($x[1]) ?></span><h3><?= $escape($x[2]) ?></h3><p><?= $escape($x[3]) ?></p><a class="text-link" href="<?= linkTo('contact') ?>">Talk to a specialist <span>→</span></a></article><?php endforeach; ?></div><p class="muted-note">Editorial content is being prepared. Published resources will be reviewed for accuracy and kept current.</p>
  <?php elseif($page['type']==='faq'): ?><div class="faq-list"><?php foreach([['Where does X-Security operate?','Service coverage depends on the assignment and applicable licensing. Contact us with your location and requirements.'],['How does an engagement begin?','We start with a confidential, high-level conversation, agree scope and confirm any legal, safety or authorization requirements.'],['Can services be combined?','Yes. When useful, we can coordinate investigation, cyber, protection and risk intelligence specialists around a single client need.'],['Do you provide cybersecurity testing?','We offer authorized defensive assessments and testing. All technical testing requires documented authorization and a clear scope.'],['How do you handle confidentiality?','Confidentiality is addressed during scoping. Please avoid sending sensitive operational details through a general website form.'],['What training do your personnel receive?','The proposed model includes a shared professional foundation followed by role-specific assessment and continuous development.'],['Can you support events and venues?','We provide event and venue security planning and personnel, subject to scope, availability and applicable requirements.'],['What credentials do you hold?','Only verified and current credentials applicable to the service and jurisdiction will be represented. Contact us for current details.']] as $x): ?><details><summary><?= $escape($x[0]) ?><span>+</span></summary><p><?= $escape($x[1]) ?></p></details><?php endforeach; ?></div>
  <?php elseif($page['type']==='contact'): ?><div class="contact-layout"><div class="contact-aside"><p class="eyebrow">A GOOD BRIEF STARTS HERE</p><h2>Tell us the<br><em>shape of the challenge.</em></h2><p>Share only what is needed for us to route your inquiry. Do not include sensitive operational, personal or security details in this form.</p><div class="contact-meta"><span>CONFIDENTIALITY</span><p>We will use the information to respond to your inquiry. Do not send sensitive attachments through this form.</p></div><div class="contact-meta"><span>OFFICE INFORMATION</span><p>Official office address, telephone and monitored email to be added when confirmed.</p></div></div><div class="form-panel"><?php if($sent): ?><div class="success-panel"><span>✓</span><h3>Demo submission complete.</h3><p>This demo did not transmit or store your information.</p></div><?php else: ?><form method="post" action="<?= linkTo('contact') ?>" novalidate><input type="hidden" name="csrf" value="<?= $escape($_SESSION['csrf']) ?>"><div class="honeypot" aria-hidden="true"><label>Website <input name="website" tabindex="-1" autocomplete="off"></label></div><?php if($error): ?><div class="form-error" role="alert"><?= $escape($error) ?></div><?php endif; ?><div class="form-grid"><label class="field span-two">What support are you looking for?<select name="need" required><option value="">Select a service</option><option>Private investigation</option><option>Cybersecurity & technology</option><option>Executive or venue protection</option><option>Protective intelligence & risk</option><option>Training</option><option>Other</option></select></label><label class="field">Your name<input name="name" autocomplete="name" required></label><label class="field">Work email<input type="email" name="email" autocomplete="email" required></label><label class="field">Organization <span>(optional)</span><input name="organization" autocomplete="organization"></label><label class="field">Timeframe<select name="urgency"><option>General inquiry</option><option>Within 30 days</option><option>Within 7 days</option><option>Urgent</option></select></label><label class="field span-two">Brief description<textarea name="description" rows="4" maxlength="1200" placeholder="A high-level summary is enough. Please do not share sensitive operational details."></textarea><small>Maximum 1,200 characters.</small></label><label class="consent span-two"><input type="checkbox" name="consent" value="yes" required><span>I agree that X-Security may use these details to respond to my inquiry.</span></label><div class="span-two"><button class="button button-accent" type="submit">Send inquiry <span>↗</span></button><p class="form-caption">Demo form only. No information is sent or stored.</p></div></div></form><?php endif; ?></div></div>
  <?php endif; ?>
  </section>
<?php endif; ?>
</main>
<footer class="site-footer"><div class="footer-main"><div class="footer-brand"><a class="brand" href="<?= linkTo('home') ?>"><span class="brand-mark">X</span><span class="brand-name">X-SECURITY<small>INTELLIGENCE · PROTECTION · TRAINING</small></span></a><p>Integrated security capability for complex challenges.</p></div><div><span class="footer-heading">CAPABILITIES</span><a href="<?= linkTo('services') ?>">All services</a><a href="<?= linkTo('investigations') ?>">Private investigation</a><a href="<?= linkTo('cybersecurity') ?>">Cybersecurity</a><a href="<?= linkTo('protection') ?>">Protection</a><a href="<?= linkTo('risk') ?>">Risk intelligence</a></div><div><span class="footer-heading">X-SECURITY</span><a href="<?= linkTo('about') ?>">About</a><a href="<?= linkTo('training') ?>">Training</a><a href="<?= linkTo('careers') ?>">Careers</a><a href="<?= linkTo('compliance') ?>">Compliance</a><a href="<?= linkTo('cases') ?>">Client success</a></div><div class="footer-cta"><span class="footer-heading">START A CONVERSATION</span><p>Tell us what you need. We’ll help define a clear next step.</p><a class="text-link link-light" href="<?= linkTo('contact') ?>">Contact X-Security <span>↗</span></a></div></div><div class="footer-bottom"><span>© <?= date('Y') ?> X-Security. All rights reserved.</span><span>CONFIDENTIALITY · INTEGRITY · PROFESSIONALISM</span><a href="<?= linkTo('faq') ?>">FAQ</a></div></footer>
<a class="mobile-cta" href="<?= linkTo('contact') ?>">Request consultation <span>↗</span></a>
</body></html>
