expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2
zend.assertions = -1
memory_limit = 128M
max_execution_time = 30
max_input_time = 30
post_max_size = 2M
upload_max_filesize = 1M
max_file_uploads = 0
session.save_path = /tmp
upload_tmp_dir = /tmp
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 64
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 0
session.use_strict_mode = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
session.cookie_secure = 1
session.cookie_samesite = Lax
